### ISSUE TITLE
#[derive(Default)] doesn't work

### ISSUE THREAD

**Issue by veniamin-ilmer** [danlehmann/bitfield#1]
This gives me an error..
```
#[derive(Default)]
#[bitfield(u8, default: 0)]
struct ROMAddress {
  #[bits(0..=7, rw)]
  offset: u8,
}
```

Is there a more correct way for me to do this? Current work around is to use the `new` function.

**Comment by danlehmann** [comment]
I'm not at my machine right now but you could try to swap the two lines:

#[bitfield(...)]
#[derive(Default)]

Please let me know if it fixes the issue. If not, I can look into this in more detail in the next few days.

**Comment by veniamin-ilmer** [comment]
This worked, thank you. I didn't realize order mattered.

**Comment by danlehmann** [comment]
Glad to hear this fixed your problem.

The reason why the order matters is that bitfield will pass-through other attributes (like derive), but derive doesn't seem to extend the same courtesy. I don't know of a way to fix that on my end.

One more thing that's worth mentioning: derive(Default) will initialize the bitfield to 0, even if you specify another value in [default: x], which I think is not great. The best solution would probably be for the macro to implement the Default trait if a "default: x" value is specified. Unfortunately, this will break your build (as you'd then end up with two default implementations). As it's a potentially breaking change, I'll put it behind a major version change (unless I can make it backwards compatible somehow). Just wanted to give you a heads-up - to fix it, you'd simply have to remove the derive(Default) again after you update.

**Comment by danlehmann** [comment]
I tried to emit a warning if derive(Default) is specified to avoid the conflict, but unfortunately macros can not emit warning in stable Rust yet. So it will be hard compiler error going forward - to resolve, just remove the manual derive(Default) once you update.
