### ISSUE TITLE
Support  #[cfg(test)] in enums

### ISSUE THREAD

**Issue by danlehmann** [danlehmann/bitfield#13]
In bitenums it would be useful to selectively disable certain values via
`#[cfg(test)]`

Maybe this would also make sense in regular bitfields?

**Comment by danlehmann** [comment]
This affects exhaustive-ness checks. How do we know that everything is covered? Also, depending on the cfg, we might be exhaustive or not exhaustive.

One way to solve this would be:
- if cfg exists, the bitenum must be marked as non-exhaustive (or not marked at all, as that's the default)
- once cfg exists, exhaustive-ness checks are disabled

One downside of this however that if we ever manage to perform this check even with conditionals, we'd be stuck with an invalid flag. So maybe it makes more sense to have this be more explicit?

"exhaustive: conditional" could cover that for example

**Comment by hecatia-elegua** [comment]
As this is not a feature of normal rust enums, I'm not so sure about adding this here, as it's not related to bitfields-only.
Any usecases?
Different Names for same numbers don't seem useful, maybe only a little to self-document.
Different numbers for same names is completely confusing.
Turning off certain variants seems the most useful, but only for long enums.
i.e.
```rust
enum Foo {
  Zero = 0b00,
  #[cfg(a)]
  One = 0b01,
  #[cfg(not(a))]
  Two = 0b02,
}
```
could be
```rust
#[cfg(a)]
enum Foo {
  Zero = 0b00,
  One = 0b01,
}
#[cfg(not(a))]
enum Foo {
  Zero = 0b00,
  Two = 0b02,
}
```
which duplicates to some extend but is fine for short enums.

**Comment by danlehmann** [comment]
Hey!

This is a feature of normal rust enums: You can have members that only exist based on cfg (tried it).

The point here is less to have a member that exists with different names - I only did that in a unittest for correctness. The main reason is to disable a value completely.

The use-case that came up for me was that I a bitenum that had a certain value only in cfg(test) configurations - in non-test environments this member simply didn't make any sense. Specifically, this was for a syscall code definition where unittests have a syscall that regular code doesn't get. Rust supported this just fine, but the constructor and exhaustiveness-check of bitenum failed. So I wanted to add this to have feature parity with regular rust enums

**Comment by hecatia-elegua** [comment]
You're right, I only found unrelated stuff, now searched it again and found https://github.com/rust-lang/rust-clippy/issues/9607
