### ISSUE TITLE
u1 struct fields

### ISSUE THREAD

**Issue by p00f** [danlehmann/bitfield#16]
Sometimes I do really want a single bit which is not a bool:

https://wiki.osdev.org/X86-64_Instruction_Encoding#REX_prefix

The `r`,`x`,and `b` fields are single-bit extensions, same with VEX/XOP prefixes further down the page
```rust
#[bitfield(u8)]
pub(crate) struct RexPrefix {
    #[bits(2..=2,r)]
    pub(super) r: u1,
    #[bits(1..=1,r)]
    pub(super) x: u1,
    #[bits(0..=0,r)]
    pub(super) b: u1,
}
```
However, it gives this compilation error:
```
error: custom attribute panicked
   --> src/amd64/types.rs:274:1
    |
274 | #[bitfield(u8)]
    | ^^^^^^^^^^^^^^^
    |
    = help: message: bitfield!: Field r has datatype u1, which is not supported. Use bool instead
```

**Comment by danlehmann** [comment]
Actually, this was fairly straightforward to implement. Could you give this a quick try? In your cargo.toml, change to this:

```
bitbybit = { git = "https://github.com/danlehmann/bitfield", branch = "allow-u1-in-bitfield" }
```

Let me know if this works for you.

**Comment by p00f** [comment]
Thanks, that works!
