### ISSUE TITLE
Creating structure whose size is greater than u128 

### ISSUE THREAD

**Issue by mohit1018102** [danlehmann/bitfield#18]
I'm facing a issue while porting a huge structure of C/c++ . Structure using bitfields, total size of structure is greater then u128 how can I implement such occurrences.

#[bitfield(u256)]
^^^^^^^^^^^^^^^^^
help : message : bitfield! : Supported values for base data type are u8, u16, u32, u64, u128. u256 is invalid.

**Comment by hecatia-elegua** [comment]
Depending on what exactly this structure does, you can split it, i.e.
```rust
#[bitfield(u128)]
struct Header {
//...
}
#[bitfield(u128)]
struct Body {
//...
}
/* no attribute here */
struct FullThing {
  header: Header,
  body: Body
}
```
(with better names of course)

**Comment by danlehmann** [comment]
Could you say more about your usecase? I've used bitfield in some larger structures (for example PCIe definitions), but in the end it was always bitfields within structs, as @hecatia-elegua said.

**Comment by mohit1018102** [comment]
Hi @danlehmann , actual there a C/C++ structure of size 256 bytes, but can be done using approach mention by @hecatia-elegua , thank you for the suggestion 😄.

**Comment by mohit1018102** [comment]
Issue resolved
