### ISSUE TITLE
Missing documentation warning

### ISSUE THREAD

**Issue by veniamin-ilmer** [danlehmann/bitfield#2]
First, thank you for your crate. I have been using it successfully to set booleans and nibbles inside of bytes for my chip emulator.

Recently I started documenting all of my code. I added in `#![warn(missing_docs)]` as a way for the compiler to tell me if documentation is missing anywhere. This has been useful for me to find any undocumented functions or structures.

Then, I came to my bitfield structs and ran into a problem. Here is an example:

```
#![warn(missing_docs)]

/// Store register and character index
#[bitfield(u8, default: 0)]
pub struct Registers {
  /// Register Index
  #[bits(4..=7, rw)]
  reg_index: u4,

  /// Character Index
  #[bits(0..=3, rw)]
  char_index: u4,
}
```

The compiler gave me a warning:
```
warning: missing documentation for an associated function
 --> src\i8080.rs:7:1
  |
7 | #[bitfield(u8, default: 0)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
```

I don't really understand why the compiler is throwing this warning.
I tried putting the documentation comment between the #[bitfield] and the struct, but it still gave me the warning..

**Comment by danlehmann** [comment]
Thanks for the report! I'll have a fix for this shortly

**Comment by danlehmann** [comment]
I added doc comments to the everything that's public. Would you mind giving this a quick try before I post to crates.io?

You can use the version from github by changing your dependency to this:
bitbybit =  { git = "https://github.com/danlehmann/bitfield" }


If this fixes your issue, I'll post a new version.

**Comment by veniamin-ilmer** [comment]
I confirm, no more error. I see you also derive default too, so I removed that extra derive line from my code.

**Comment by danlehmann** [comment]
Yes. I added some more context on https://github.com/danlehmann/bitfield/issues/1 to explain why this became a hard error.

Just uploaded 1.1.1 to crates.io.
