### ISSUE TITLE
Support `set_*` methods which can be called by mutable reference

### ISSUE THREAD

**Issue by mtoohey31** [danlehmann/bitfield#56]
I often find myself writing things like:

```rust
page_table[pti] = page_table[pti].with_read_write(write);
```

...where I have to repeat the reference to the object I'm dealing with on both sides of the assignment when I just want to change one field. (I don't think there's currently any better alternative, let me know if I'm missing something though.) It'd be nicer to be able to write something like:

```rust
page_table[pti].set_read_write(write);
```

I realize that both would probably compile to the same machine code, but I'd prefer the second regardless just cause I think it's easier to read. As mentioned in the title, these could be generated as methods that operate on a mutable reference to the bitfield type, for any field that is declared as writable. I'd be willing to implement it myself, if you're interested in supporting this feature.

**Comment by danlehmann** [comment]
Implemented and will roll out as part of next release
